JavaScript field validators for form fields.
kitodo/kitodo-publication pull request #211
Opened 2021-07-02 13:11 UTC by haogatyp

#CMR-91

2021-07-12 11:17 UTC, claussni requested changes

2021-07-12 11:17 UTC, claussni commented on Resources/Public/JavaScript/formvalidators.js
> +var isDate = function(value) {
File needs copyright header

2021-07-14 15:13 UTC, haogatyp commented on Resources/Public/JavaScript/formvalidators.js
> +var isDate = function(value) {
I added the copyrigh header.

2021-07-15 10:45 UTC, claussni approved these changes

2021-07-15 10:45 UTC, merged