Added a GND keyword autocomplete and a lokal data autocomplete.
kitodo/kitodo-publication pull request #213
Opened 2021-07-02 13:14 UTC by haogatyp

#CMR-109

2021-07-14 15:41 UTC, haogatyp commented on Classes/Controller/AbstractDocumentFormController.php
> +use EWW\Dpf\Services\FeUser\GndDataService;
Unused imports have been removed.

2021-07-23 08:37 UTC, claussni requested changes
Please resolve conflict with master

2021-07-23 12:43 UTC, haogatyp commented
Conflicts are resolved.

2021-09-02 13:30 UTC, claussni approved these changes

2021-09-03 05:42 UTC, merged