Suggestion management
kitodo/kitodo-publication pull request #241
Opened 2022-02-23 16:26 UTC by haogatyp

Resolves https://jira.slub-dresden.de/browse/CMR-1074

2022-03-17 09:40 UTC, claussni approved these changes

2022-03-22 09:39 UTC, claussni requested changes
Please rebase

2022-03-22 13:32 UTC, haogatyp commented
Rebase is done.

2022-03-23 08:51 UTC, claussni approved these changes

2022-03-28 12:45 UTC, merged